### ISSUE TITLE
include/3 predicate hard to find, suggest 'filter/3'

### ISSUE THREAD

**Issue by malteneuss** [SWI-Prolog/issues#12]
The include predicate goes through a list and only keeps those elements that succeed on a given goal.
The name seems a little vague. In the context of functional programming such an operation on a list is mostly called filter. Thus i suggest adding a new predicate 'filter' as a clone of 'include'.

**Comment by triska** [comment]
Before `include/3`, the predicate used to be called `sublist/3`. I consider `include/3` a huge improvement upon the previous name, because the opposite (`exclude/3`) is natural and very easy to remember. What would be the opposite of `filter/3`

Note that all these predicates are only sound if their arguments are sufficiently instantiated. In other cases, they may incorrectly cut away solutions. [A recent paper](http://www.complang.tuwien.ac.at/ulrich/papers/PDF/2015-kps-3.pdf) contains more information about how to make such constructs pure.

**Comment by JanWielemaker** [comment]
`fixed' by adding entries in the documentation index.
