### ISSUE TITLE
Wrong result from X is -1**2.

### ISSUE THREAD

**Issue by RECHE23** [SWI-Prolog/issues#123]
Hi!

I have noticed that the order of operations is wrong for negation and exponentiation...

`X is -1**2.` should return `X = -1.` but it returns `X = 1.`

I am using SWI-Prolog (threaded, 64 bits, version 9.0.4) on Mac OS.

**Comment by JanWielemaker** [comment]
??  Y**2 is the same as Y*Y and -1*-1 is 1.    What am I missing?

**Comment by RECHE23** [comment]
Since we are dealing with a numerical value, `-1**2` should equal `-(1**2)`, not `(-1)**2`.

If we have `X is -1, Y is X*X.` or `X is -1, Y is X**2.`, the behaviour is correct : it returns 1.

**Comment by JanWielemaker** [comment]
> numerical value, `-1**2` should equal `-(1**2)`, not `(-1)**2`

Well, Prolog syntax works differently .   The term is read as `**(-1, 2)`.  `-1` is read as integer.   Even if we would write `-(1)**2`, operator precedence reads this as `**(-(1),2)` and we still get 1.

**Comment by RECHE23** [comment]
But why would `X is -1**2.` return `X = 1.` when `Y is 1, X is -Y**2.` returns `X = -1.`?

This is incoherent behaviour and it doesn't respect the standard operator precedence...

**Comment by EricGT** [comment]
Checked the ISO standard for Prolog. The standard operators are listed in `Table 7 - The operator table`

To keep the list short will only show the relevent parts

Priority   Specifier   Operator(s)
500       yfx            + - 
400       yfx            * /  //  rem mod
200       xfx            **
200       xfy            ^   - This is not the exponentiation but the [caret operator](https://www.swi-prolog.org/pldoc/man?section=allsolutions)  
200         fy            -

From 6.3.4 
> A lower priority means stronger operator binding.

The negative sign with -1 binds strong than ** with 2.

So as Jan notes `Prolog syntax works differently` and thus it should be noted about the differences and parenthesis used as needed.

HTH

**Comment by JanWielemaker** [comment]
Still, because `-1` is read as an integer.   That is defined such by the standard and all Prolog systems on my machine agree to this.    I was not involved when this was decided, but I can think of a good reason.  Consider e.g.   `mynum(-1).` as fact and the query `?- X is 2-3, mynum(X).`   If we would not read -1 as an integer this query would fail.   In functional languages this is not a problem because `-(1)` is always evaluated and thus the same as the negative integer.    In Prolog, one is a term and the other an integer and thus they do not compare equal as terms, but only using `=:=/2`.
