### ISSUE TITLE
"Singleton variable in branch" warning with the optimise flag and debug/3

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/issues#52]
With the following source file:

```
foo :-
    (   x == x
    ->  succ(0, X),
        debug(foo, "~w~n", [X]) 
    ;   true
    ).
```

and then, from the toplevel:

```
$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.1-1-ge34c2e760)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- set_prolog_flag(optimise, true).
true.

?- [test].
Warning: /home/boris/code/arch/test.pl:1:
	Singleton variable in branch: X
true.
```

I noticed it while trying to use library(http/http_client):

```
?- set_prolog_flag(optimise, true).
true.

?- use_module(library(http/http_client)).
Warning: /home/boris/lib/swipl-7.5.1/library/http/http_wrapper.pl:98:
	Singleton variable in branch: Method
	Singleton variable in branch: Location
Warning: /home/boris/lib/swipl-7.5.1/library/http/http_header.pl:110:
	Singleton variable in branch: Msg
true.
```

Both cases in the library code are identical to the minimal example above.

**Comment by JanWielemaker** [comment]
This problem is caused by `library(debug)` removing the debug statement.  The resulting code analysis obviously finds a singleton, but using `_Method` results in a _multiton_.  In recent versions these cases can be fixed using _<digit>[Name] for the variable naming as the system never emits single/multiton messages on variables names _<digit>*.

I propose to use `_0`_Name_ as a convention.

Pull requests are welcome :)
