### ISSUE TITLE
issues tracking

### ISSUE THREAD

**Issue by Anniepoo** [SWI-Prolog/issues#54]
It's possible to turn the issues tracking, project, and wiki features off in repositories. 

Would it be a good idea to turn off issues for most of the packages and put a note in the description leading them to this repo?

Similar questions for Projects and Wiki.

**Comment by JanWielemaker** [comment]
I don't know.   Typically I don't mind too much where the issue is filed and if it is indeed with the right package that is practical, especially when it is left open.   I could imagine that for causal users it is more practical to have it all in one place.   Just having a link in the description is unlikely to work as people do not read that.   I also understood closing this down is typically done for no-longer-maintained projects.  I don't want to give that impression!  Would be more interesting if we could link/merge the issue tracker of multiple repositories.

The wiki and projects per package are surely adequate.

**Comment by vext01** [comment]
This begs the question: what is the "issues" repo for? ;)

**Comment by JanWielemaker** [comment]
It doesn't work very well.  Ideally I guess I'd like to have one issue tracker over multiple repos, but that is AFAIK not available.  Let us keep the mess for now :)
